# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/02/17 06:50:43 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	tokenizer
DEPS		=	shared

include ../common-prelude.mk

SRC			=	tokenizer.c

include ../common.mk
