# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/12 07:00:21 by kiroussa          #+#    #+#              #
#    Updated: 2024/03/21 22:01:01 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		=	shared

include ../common-prelude.mk

SRC			=	env/msh_env_defaults.c \
				env/msh_env_free.c \
				env/msh_env_get.c \
				env/msh_env_populate.c \
				env/msh_env_tab.c \
				env/msh_env_tab_free.c \
				io/msh_fileno.c \
				io/msh_get_hostname.c \
				io/msh_is_directory.c \
				io/msh_is_interactive.c \
				io/msh_resolve_path.c \
				signal/msh_signal_handler.c \
				signal/msh_signal_init.c \
				signal/msh_signal_setdfl.c \
				msh_destroy.c \
				msh_exit.c \
				msh_init.c

include ../common.mk
